# Generated by Django 4.0.4 on 2022-05-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Tema', models.CharField(max_length=255)),
                ('Contenido', models.TextField()),
                ('Equipo', models.IntegerField()),
                ('Posteador', models.CharField(max_length=255)),
            ],
        ),
    ]
