# Generated by Django 4.0.4 on 2022-05-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0002_rename_usuario_colaborador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='Equipo',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='leadteam',
            old_name='Equipo',
            new_name='team',
        ),
    ]
