# Generated by Django 4.0.4 on 2022-05-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0004_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Team',
            new_name='team',
        ),
    ]
