# Generated by Django 4.0.4 on 2022-05-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0005_rename_team_team_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Equipo',
        ),
        migrations.RenameModel(
            old_name='LeadTeam',
            new_name='LiderDeEquipo',
        ),
    ]
